CREATE TABLE orders (
    id          INT AUTO_INCREMENT PRIMARY KEY,

    user_id     INT,
    FOREIGN KEY (user_id) REFERENCES users(id),

    status      ENUM('UNPAID', 'PAID', 'PROCESSING', 'SHIPPED', 'RECEIVED'),

    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);